### PR TITLE
Re-implement undercover localization

### PR DESCRIPTION
**Pull request by Silence-112**
## What type of PR is this?
1. [ ] Bug
2. [x] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:
Added the undercover stringtable stuff back

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

Ensure undercover related text still shows up as intended

Also needs a Russian translation (Hey... @wersal454)

### How can the changes be tested?
Steps:
Test undercover as usual

********************************************************
Notes:

### CODE REVIEW

**Comment by wersal454** [comment]
No need in translation, everything is already there

**Comment by Silence-112** [comment]
that would be because I forgot to add them to the stringtable... ahem

**Review by wersal454 — CHANGES_REQUESTED** [review]
<Original Undercover not allowed in current civ template. /Original>
            <Russian Вы не можете быть под прикрытием в текущем гражданском шаблоне /Russian>

**Review by wersal454 — CHANGES_REQUESTED** [review]
<Original An enemy military base has detected you!/Original>
            <Russian Вас обнаружила вражеская военная база/Russian>

Sounds really stupid, but it's the same translation as "An enemy outpost or seaport has detected you!" basically

**Pull request merged**
