### PR TITLE
CUP Norwegian Armed Forces

### PR DESCRIPTION
**Pull request by Azodion**
## What type of PR is this?
1. [ ] Bug
2. [x] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:
Added Flex7103's CUP Norwegian Armed Forces to Occupants in Temperate and Arctic - [Main Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3333292879)
Added Support for Norwegian F-16 Firewill Retexture - [Submod](https://steamcommunity.com/sharedfiles/filedetails/?id=2926874909&searchtext=Norwegian)
Added Support for SFP Vehicles - [Submod](https://steamcommunity.com/workshop/filedetails/?id=826911897)
### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:
********************************************************
Notes:
Should Work

### CODE REVIEW

**Review by Silence-112 — APPROVED** [review]
Seems fine, have you put the black market vehicles in our sheet?

**Comment by Azodion** [comment]
> Seems fine, have you put the black market vehicles in our sheet?

i have not, they are mostly CUP items, So I copied the prices from the sheet for those. Only one that isn't CUP or SFP, is the F-16 which I can put on the sheet though.

**Comment by Silence-112** [comment]
The sheet isn't only for pricing, we also have a python script to pull the data from it and create dealer macros ([CSV Parser](https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate/tree/stable/Tools/csvparser))

Without them in the sheet there's a possibility of them being lost next time we update it

**Comment by Azodion** [comment]
gotcha, will update the sheet with everything then :)

**Comment by Azodion** [comment]
Everything should be updated on the sheet now 👍

**Pull request merged**
