### PR TITLE
Added additional civilian helicopters

### PR DESCRIPTION
**Pull request by wersal454**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Added additional civilian helicopters   

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
I need a command to spawn ambient helicopter flyby 
********************************************************
Notes:
O_Heli_Light_02_unarmed_F is originally OPFOR ,so there is potential that rebels(AI) will try to shoot them. But I think they won't. Needs testing

### CODE REVIEW

**Comment by stutpip123** [comment]
DLC vehicles need to check whether the DLC is enabled. i think examples of that can be seen in some of the existing templates like vanilla.

see this extract from sections of Vanilla_AI_NATO_Arid.sqf

private _hasWs = "ws" in A3A_enabledDLC;
private _hasMarksman = "mark" in A3A_enabledDLC;
private _hasLawsOfWar = "orange" in A3A_enabledDLC;
private _hasTanks = "tank" in A3A_enabledDLC;
private _hasApex = "expansion" in A3A_enabledDLC;
private _hasHelicopters = "heli" in A3A_enabledDLC;
private _hasContact = "enoch" in A3A_enabledDLC;

if (_hasHelicopters) then {
    _transportHelicopters append ["B_Heli_Transport_03_F", "B_Heli_Transport_03_unarmed_F"];
};

private _policeVehs = if (_hasContact) then {
    ["B_GEN_Offroad_01_covered_F", "B_GEN_Offroad_01_comms_F", "B_GEN_Offroad_01_gen_F"]
} else {
    ["B_GEN_Offroad_01_gen_F"]
};

**Comment by wersal454** [comment]
image
screenshot is from + but since the code is the same it should work fine. I think it good to go. For 100% certainty , try it out.

**Comment by wersal454** [comment]
UPDATE!!!! 
still need work!

**Comment by wersal454** [comment]
bug
image

**Comment by wersal454** [comment]
Everything will work now.

**Pull request merged**
