### PR TITLE
CUP civ vehicle pack

### PR DESCRIPTION
**Pull request by wersal454**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Added Civilian addonVehicle pack from CU[     

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Probably yes.)

### How can the changes be tested?
Steps: 
Run around cities
********************************************************
Notes:
I know that I messed up in requiredAddons[] = {"CUP_Vehicles"}; , I just don't know what to wright there(I haven't done AddonVics stuff before).

### CODE REVIEW

**Comment by wersal454** [comment]
Also I want to add this.
["vehiclesCivHeli", ["C_Heli_Light_01_civil_F", "C_IDAP_Heli_Transport_02_F", "O_Heli_Light_02_unarmed_F"]] call _fnc_saveToTemplate;

["variants", [
    ["C_IDAP_Heli_Transport_02_F", ["Blue",1]],
    ["O_Heli_Light_02_unarmed_F", ["Light",1]]
]] call _fnc_saveToTemplate;

"O_Heli_Light_02_unarmed_F" won't be in final version since it is OPFOR

**Comment by stutpip123** [comment]
are logistics nodes already sorted for everything, mainly the trucks? also some helis, like the Mi-8 variants, are capable of carrying crates, so should probably have logistics nodes added like has been done in Unsung

**Comment by wersal454** [comment]
@stutpip123 
I really don't know stutpip. You have CUP templates right? Soooo, maybe logistics nodes already sorted?? Again idk I'm not a pro at this. 

One heli has variant VIV(it can carry vehicles) and a bunch of other vehicles with interesting capabilities.

**Comment by stutpip123** [comment]
CUP_AirVehicles_Core is a valid CfgPatches entry for detecting CUP Vehicles mod.

**Comment by wersal454** [comment]
So apparently guys from CV fixed my PR by removing some vehicles(?). I don't know if it works in the end of the day but I will leave a link to CV PR so you guys can check it out.

https://github.com/official-antistasi-community/A3-Antistasi/pull/2919

P.S. sorry guys i don't have time to test their changes and fix my PR here so if you have spare time to check what they done and remove cars if they are cosing problems, 
P.S. P.S. please don't remove planes and helis like they did, if they are causing problems than it's sucks, but I really want them to be in this PR so the latest random encounter with planes(and helis) work like it should.

**Comment by wersal454** [comment]
Well I'm blind as mole, I guess in the end it was a f*cking comma that caused the issue. Should work now, need someone to test first.

Update to the comment above: please don't remove any vehicles]

**Comment by Silence-112** [comment]
No vehicles should need removing, iirc they already work fine

I'll test it to double check though

**Comment by wersal454** [comment]
> No vehicles should need removing, iirc they already work fine
> 
> I'll test it to double check though

Thanks for fixes! On the small note, I called it vehicles pack because there is not only cars but boats, planes, helis and e.t.s. but this is just a small detail, so I think it doesn't matter as long as it works.

**Comment by Silence-112** [comment]
Good point, i'll change it back to vehicle

**Pull request merged**
