### PR TITLE
VN Factions Face and Voice changes

### PR DESCRIPTION
**Pull request by Androkiller**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Faces for VN Reb Factions where not Asian thus has been changed.

Voice VIE is a muted voice, no calls are made. This voice is need for the Ambient sound module in S.O.G which is not present for the mission. I have therefore changed to the next best thing available Chinese

### Please specify which Issue this PR Resolves.
N/A

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Recruit AI and now they make calls in Chinese when given commands or reporting

********************************************************
Notes:
Antistasi the Mod, also has the same issue, so could be changed to VIE if they implement the ambient module, however this is not for for Radio reports but only proximity based to enemy units.

### CODE REVIEW

**Comment by stutpip123** [comment]
the module cannot be implemented because would create a permanent SOGPF dependancy (could be done for SOGPF maps only i suppose)

**Comment by stutpip123** [comment]
changes look fine to me

**Comment by Androkiller** [comment]
> the module cannot be implemented because would create a permanent SOGPF dependancy (could be done for SOGPF maps only i suppose)

 haven't quite worked out the best way to implement, but i would assume under the mission sqm for both VN maps.  looks like the module requires just to be present, but its not quite the same as call outs just ambient sound when in proximity.

**Comment by Androkiller** [comment]
So editing the mission with the module present results in the module not working. This is due to the module is reliant on the actual units being part of the faction are present, as in the unit class name needs to be present from the correct faction. 
Due to how antistasi creates units from templates the correct unit class names are not present. Hence the module will not work and would require an additional mod ontop to make it work.
So looks like Chinese is the closest one will get when playing antistasi.

**Comment by Silence-112** [comment]
I'll test this at some point and see if all is good. Is there anything else you want to add?

**Comment by Silence-112** [comment]
PR looks good. Links have been added on [_this_](https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate/wiki/Developers#androkiller---vn-factions-face-and-voice-changes-85) page.

Feel free to open more pulls in the future, only together can we encompass as much as possible

**Pull request merged**
