### PR TITLE
Reaction Forces Templates

### PR DESCRIPTION
**Pull request by Silence-112**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Added Reaction Forces templates from [Community PR 3185 (Tiny-DM)](https://github.com/official-antistasi-community/A3-Antistasi/pull/3185)

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:
Load RF CDLC;
Load one of the compatible RF templates (Most of the vanilla ones);
Enable RF CDLC in additional content;
Ensure RF assets are being used

********************************************************
Notes:

### CODE REVIEW

**Comment by wersal454** [comment]
Don't forget about elite loadouts, probably can copy special forces stuff, except silencers for weapons, also I don't see new sniper rifle and "deagle"(deagle is debatable, but Special forces or elites might use it)

**Comment by Tiny-DM** [comment]
The new sniper rifle was not added, as it replaces the rebels' normal starting SMGs. It was considered to give the weapon to DMRs/Snipers, but a 5.56 round does not carry velocity nearly far enough to work at all as a sniper weapon, and giving a DMR a bolt-action weapon, especially chambered in a caliber as small as 5.56, was considered but not added. There is most likely precedent in other templates, but vanilla armor is good enough to render the rifle only effective enough for the rebels.

Deagles were not added primarily because semi/auto Glocks are typically a much more lore accurate and realistic weapon for soldiers to use, and also because I didn't want to have to deal with trying to give them a special handgun for consistency.

Also, make sure you pull the WS_Civ faction from the templates list, as that appears to be a template not present in this version of Antistasi.

**Review by wersal454 — CHANGES_REQUESTED** [review]
In vanilla civ. I missed that

if (_hasLawsOfWar) then {
    _civMedical append ["C_Van_02_medevac_F", 0.3];
};

**Comment by Silence-112** [comment]
> The new sniper rifle was not added, as it replaces the rebels' normal starting SMGs. It was considered to give the weapon to DMRs/Snipers, but a 5.56 round does not carry velocity nearly far enough to work at all as a sniper weapon, and giving a DMR a bolt-action weapon, especially chambered in a caliber as small as 5.56, was considered but not added. There is most likely precedent in other templates, but vanilla armor is good enough to render the rifle only effective enough for the rebels.
> 
> Deagles were not added primarily because semi/auto Glocks are typically a much more lore accurate and realistic weapon for soldiers to use, and also because I didn't want to have to deal with trying to give them a special handgun for consistency.
> 
> Also, make sure you pull the WS_Civ faction from the templates list, as that appears to be a template not present in this version of Antistasi.

Pretty sure I added WS_Civ in this PR. We seem to be missing quite a lot of the WS templates, I assume they were added after we forked Plus and have been forgotten in subsequent updates.
Thanks for the heads up

**Comment by wersal454** [comment]
Also don't forget about, rivals

**Comment by Silence-112** [comment]
Rivals added, ideally want someone else to confirm templates are working with RF cdlc enabled

**Comment by wersal454** [comment]
Seems to work for the most part. No error messages. Black market stuff works. Some small issues + missing some stuff.

**Pull request merged**
