### PR TITLE
Small adjustments and fixes

### PR DESCRIPTION
**Pull request by wersal454**
## What type of PR is this?
1. [x] Bug
2. [x] Change
3. [x] Enhancement
4. [x] Miscellaneous

### What have you changed and why?
Information:

See the commits discription to see the changelog

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:

### CODE REVIEW

**Comment by Silence-112** [comment]
Small adjustments, 144 files changed?

**Comment by wersal454** [comment]
> Small adjustments, 144 files changed?

if you exclude ```SMGs!!!``` kinda small

**Comment by Silence-112** [comment]
Could you do each change in a standalone PR?
Also wont adding the SMGs to the selectRandom just break if there are no SMG entries?

**Comment by wersal454** [comment]
> Could you do each change in a standalone PR? Also wont adding the SMGs to the selectRandom just break if there are no SMG entries?

Well... I could, but I already did THIS + when stuff goes to testing and afterward gets merged into unstable, it all comes out of a single PR anyway

If SMGs are not present, it should select any non empty element(I think) + in every template that I added smgs to, they are present(crewman use them and such)

**Comment by Silence-112** [comment]
*If* it gets merged, it's still better to have things compartmentalized. If anything breaks it's much easier to figure out what broke it when you only have to go through a few changes per PR rather than 100

If it isn't immediately relevant, or reasonably small (along with the main pull), it shouldn't be in a PR this big. It also means that in order to merge any one fix, we have to merge the 100 other things too

**Pull request closed without merging**
