### PR TITLE
Combat landing + auto smoke overhaul

### PR DESCRIPTION
**Pull request by wersal454**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:

I noticed that in C.V. heli qrf dropes smoke upon landing. And while I was at it I thought maybe I'll make sure that helis(vtols) won't explode upon landing.
Also wanted to add flares while heli landing and after it gets an order to rtb     

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
spam QRFAIR support
********************************************************
Notes:
I left commented out code that I personally would like to make a reality, but for now I can't figure it out

Also thinking about creating an issue on github with all the issues known, discord is kinda hard thing to follow.

### CODE REVIEW

**Comment by wersal454** [comment]
Also I wanted to keep engines running with this _helicopter setVehicleEngineStatus true;
But it also doesn't work

**Comment by Silence-112** [comment]
> Also I wanted to keep engines running with this _helicopter setVehicleEngineStatus true; But it also doesn't work

Probably because that command doesn't exist? Try using [engineOn](https://community.bistudio.com/wiki/engineOn)

**Comment by wersal454** [comment]
Also found why(I think) autosmokecover won't work.
```sqf
private ["_veh"];

_veh = _this select 0;

if !(alive _veh) exitWith {};

if !(local _veh) exitWith {};

private _smoked = _veh getVariable ["smoked",0];

if (time < _smoked) exitWith {};

_veh setVariable ["smoked",time + 120];

if ({"SmokeLauncher" in (_veh weaponsTurret _x)} count (allTurrets _veh) > 0) then
	{
	[_veh,"SmokeLauncher"] call BIS_fnc_fire;
	}
else
	{
	if !(A3A_hasIFA) then
		{
		private ["_pos","_smokeX"];
		_typeSmoke = selectRandom allSmokeGrenades;
		for "_i" from 0 to 8 do
			{
			_pos = position _veh getPos [(28 + random 2),_i*40];
			_smokeX = _typeSmoke createVehicle [_pos select 0, _pos select 1,getPos _veh select 2];
			};
		};
	};
```
image
Why we have such a low usage of A3A_hasIFA? Is it something from plus or "recent" addition from C.V. ?

**Comment by wersal454** [comment]
Maybe this can be used to give a heli an Iframe upon touchdown https://forums.bohemia.net/forums/topic/229294-addeventhandler-landedtouchdown-works-for-fixed-wing-aircrafts-only-workaround-for-helis/#:~:text=Try%20with%20the,FALSE%20as%20landed.
or this 
https://community.bistudio.com/wiki/isTouchingGround

**Comment by wersal454** [comment]
pay attention for smokecoverauto, I copied code from C.V. maybe it will break apc or a tank usage of smokes

**Comment by wersal454** [comment]
nmv, it works

**Comment by stutpip123** [comment]
> Also found why(I think) autosmokecover won't work.
> 
> ```sqf
> private ["_veh"];
> 
> _veh = _this select 0;
> 
> if !(alive _veh) exitWith {};
> 
> if !(local _veh) exitWith {};
> 
> private _smoked = _veh getVariable ["smoked",0];
> 
> if (time < _smoked) exitWith {};
> 
> _veh setVariable ["smoked",time + 120];
> 
> if ({"SmokeLauncher" in (_veh weaponsTurret _x)} count (allTurrets _veh) > 0) then
> 	{
> 	[_veh,"SmokeLauncher"] call BIS_fnc_fire;
> 	}
> else
> 	{
> 	if !(A3A_hasIFA) then
> 		{
> 		private ["_pos","_smokeX"];
> 		_typeSmoke = selectRandom allSmokeGrenades;
> 		for "_i" from 0 to 8 do
> 			{
> 			_pos = position _veh getPos [(28 + random 2),_i*40];
> 			_smokeX = _typeSmoke createVehicle [_pos select 0, _pos select 1,getPos _veh select 2];
> 			};
> 		};
> 	};
> ```
> 
> image Why we have such a low usage of A3A_hasIFA? Is it something from plus or "recent" addition from C.V. ?

I think its legacy code, A3A_hasIFA dates back to very old community version pre 2.3, as IFA was removed in 2.3 in summer 2021

**Comment by Silence-112** [comment]
Does this actually fix exploding helis or does the PR need a rename?

**Comment by wersal454** [comment]
> Does this actually fix exploding helis or does the PR need a rename?

```sqf
_dam = Damage _helicopter;
    if ((getPos _helicopter select 2) < 0.25 ) exitwith{_helicopter setdamage 0; sleep 1; _helicopter setdamage _dam;};
```
this line should prevent helis from taking damage on touch down... so yeah? I've tested this with VTOL's and with how fast they landing, they don't explode, but I don't know what happens if terrain is kind of finicky, but I guess this is fastrope function is for.

**Comment by Silence-112** [comment]
You know "Damage" isn't a command right?
nvm, classic case of Bohemia Interactive Syndrome

https://community.bistudio.com/wiki/damage
https://community.bistudio.com/wiki/Damage

**Comment by wersal454** [comment]
You can rename it to something like "combat landing overhaul" or "combat landing & smokecoverauto fix"

**Pull request merged**
