### PR TITLE
fix SAM

### PR DESCRIPTION
**Pull request by wersal454**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:

Just added more information for SAM about the target.    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
spawn or just play
********************************************************
Notes:
While working on cruise missile noticed that SAM spawns but doesn't target players or anything, it just shoots in the air.
Better test it.

### CODE REVIEW

**Comment by wersal454** [comment]
Also SAM function needs to be updated since it doesn't use template info and just uses vanilla vehicles.

**Comment by stutpip123** [comment]
not all sam turrets are sams. for example, the FlaK 88 in WW2, or the CIS Flak turret in Clone Wars. so if you change things it may break them

**Comment by wersal454** [comment]
> not all sam turrets are sams. for example, the FlaK 88 in WW2, or the CIS Flak turret in Clone Wars. so if you change things it may break them

Yeah, need to think about it. Adding more vehicle categories is (in my opinion) for the better, but would take goood amount of time. Maybe create some sort of list of all actual sams and make a check for it? In Faction example file or (if this will ever happen) wiki or "how to" just mention that if someone wants their new template , modset or whatever to work with SAM support they should add this vehicle to the list

**Comment by wersal454** [comment]
> not all sam turrets are sams. for example, the FlaK 88 in WW2, or the CIS Flak turret in Clone Wars. so if you change things it may break them

btw 
1. why flak turret's are in SAM category(if they are)? shouldn't they be in vehiclesAA or staticAA? I can guess the problem with staticAA since it can spawn on top of the building , but what about vehiclesAA?

2. I don't know for sure what will happen if you put flack in SAM support and I wanted to write that there is a smart system to check if vehicle actually has AA missiles, but there is none(for now(or it is not possible). What bad can happen ? It would probably try to fire at the aircraft and (probably) won't hit anything. But yeah I believe there should be a better way to detect whether SAM actually can fire missiles or just tinker with template system like I wrote above.

**Comment by stutpip123** [comment]
Because SAM are just stronger/longer range AA. So in other time periods, larger Flak serves that purpose. With the existing code, they simply spawn at an airbase, with crews as one squad. They seem to function fine, as most static turrets do, only needing to target and eliminate enemies within their range.

**Comment by Silence-112** [comment]
Looking at the wiki page for confirmSensorTarget and reportRemoteTarget, this should still in theory work with flak.

Of course it'll need testing, but i'm happy to merge it if you're fine with it @wersal454

**Comment by wersal454** [comment]
> Looking at the wiki page for confirmSensorTarget and reportRemoteTarget, this should still in theory work with flak.
> 
> Of course it'll need testing, but i'm happy to merge it if you're fine with it @wersal454

I'm fine with it. It's just a fix without any shenanigans with choosing sam's in the templates(I've tried it but it didn't work for some reason). I've made the same PR to CV but they still didn't respond. If you want you can wait until they write something about this fix.

**Comment by Silence-112** [comment]
> > Looking at the wiki page for confirmSensorTarget and reportRemoteTarget, this should still in theory work with flak.
> > Of course it'll need testing, but i'm happy to merge it if you're fine with it @wersal454
> 
> I'm fine with it. It's just a fix without any shenanigans with choosing sam's in the templates(I've tried it but it didn't work for some reason). I've made the same PR to CV but they still didn't respond. If you want you can wait until they write something about this fix.

I'll merge it. If you get any extra info and change the code again, open another PR

**Comment by stutpip123** [comment]
> > Looking at the wiki page for confirmSensorTarget and reportRemoteTarget, this should still in theory work with flak.
> > 
> > Of course it'll need testing, but i'm happy to merge it if you're fine with it @wersal454
> 
> I'm fine with it. It's just a fix without any shenanigans with choosing sam's in the templates(I've tried it but it didn't work for some reason). I've made the same PR to CV but they still didn't respond. If you want you can wait until they write something about this fix.

Waiting for community to comment could be years 
Those unsung templates of theirs were made by me before the mod version, didn't come out until like 6 months after the mod update.
They still haven't done anything with the improved SPE_IFA templates I pull requested 8 months ago

**Pull request merged**
