### PR TITLE
"Active Anti-artillery Defence System"

### PR DESCRIPTION
**Pull request by wersal454**
## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement
4. [x] Miscellaneous

### What have you changed and why?
Information:

This PR contains fictional systems and scenarios. Any resemblance to actual events and entities is purely coincidental. The content is designed for entertainment and illustrative purposes only and should not be interpreted as factual or reflective of real-world situations.

Now when we done with it

this is continuation of #198 with fixes and improvements
Alarm sound still doesn't work, can't figure out why(maybe for the better actually)

Also, haven't thought of this before, this will help with people abusing mortars when attacking air/mil bases

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************

### CODE REVIEW

**Review by Silence-112 — COMMENTED** [review]
I don't think our opinion on this is going to change, everything else aside it makes little sense for bases (or rebels by extension) to have these systems

This could be either pointless or really overpowered for rebels to get.

I still believe this would be better as a mod that just *works*, no need for integration directly into Antistasi. If the init functions were ran on the statics as they were spawned, it should in theory work without having to hook into Antistasi at all

**Comment by wersal454** [comment]
1. I guess you haven't played with this thing at all, it's not op, for both Rebels and AI(plus if you buy it from blackmarket all turrets cost like a leg)

2. Init does work as soon as turrets spawn, but parametr for sure won't work
(Though if it's an extender, players for sure know what they are doing(right?))

3. IRL controversial is just silly, do we ban Merkava tanks in Vanilla ? Ask Maxx, what he thinks

4. Might as well run a community poll, let players decide

**Comment by Silence-112** [comment]
I'd argue being able to stop all artillery is OP

You wouldn't need an extender at all if the actual mod "worked as-is" without having to run any extra functions

The merkava is grandfathered in just like AFRF, there would be a difference if we suddenly added an IDF faction. "Ask an Israeli" isn't a valid argument

Letting the community in whole guide the development process is a recipe for disaster, only god knows how many people have suggested "ukraine v russia" factions. It'd be an absolute shitshow if we let them guide literally every decision we make

Sure, "controversy" is "silly" but if we go out of our way to add it, it just causes arguments and problems

**Comment by wersal454** [comment]
It doesn't stop every round, + rockets ain't infinite

Original mod works as is, but it lacks support for CUP and OPTRE(+ plus every other turret we can potentially add)

Turrets ain't originally Israely, at least C-ram isn't I think

I just can't see why this a problem, I don't think I saw any bad comments under original mods

There always an option NOT to call it IRONDOME

It's not even an offensive weapon,(I.E. not meant to attack anyone, only defend)

**Comment by Silence-112** [comment]
The reason I won't approve this isn't just because it's topical at the moment, it's for multiple reasons. The functions seem to generally be poorly written and it just adds needless complexity.

Artillery counters need to be designed around the mode, not slapped in as a poor solution
I (along with other maintainers) think this just doesn't make sense in Antistasi

**Comment by wersal454** [comment]
...whatever

maintainerS, heh, sure

U do u

**Pull request closed without merging**
