### PR TITLE
Backlog features

### PR DESCRIPTION
**Pull request by wersal454**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Added gunship support  (currently works with vanilla gunships, don't know what will happen with others)
Also there are small bits of code for cruise missile support(doesn't work at all) and uav support(does work but doesn't have a code for firing it's weapons)

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
spawn support through console command or... play as usual
********************************************************
Notes:
both vtol's(gunship's) doesn't fire their weapons at infantry and nato gunship very rarely uses it's big gun
also CSAT vtol should use it's rockets but it also doesn't work
ALSO for some reason both of them sometimes spot the enemy and fly straight toward it like they are dive bombing. Probably something to do with maintaining circling course. 
Probably should make radius smaller since without mods you cannot see gunship though distance fog 
And I would love some help with this since I don't really know the arma code
Original plus branch https://github.com/igorkis-scrts/A3-Antistasi-Plus/tree/feature/gunship

### CODE REVIEW

**Comment by wersal454** [comment]
Original code for gunship probably  ̷s̷t̷o̷l̷e̷n̷  acquired by Socrates https://gitlab.com/phillyspall/blackfish-gunship-ai

**Comment by Silence-112** [comment]
So what actually works in this PR? Seems kind of pointless to merge changes that don't work correctly

**Comment by wersal454** [comment]
> So what actually works in this PR? Seems kind of pointless to merge changes that don't work correctly

Yeah... It's very WIP. So don't merge it.

**Comment by igorkis-scrts** [comment]
> Original code for gunship probably ̷s̷t̷o̷l̷e̷n̷ acquired by Socrates https://gitlab.com/phillyspall/blackfish-gunship-ai

Bruh. I haven't stole anything, in fact, you, ahem, *yoinked* the code from the very WIP and abandoned https://github.com/igorkis-scrts/A3-Antistasi-Plus/tree/feature/gunship branch where I tried to backport gunship code from old, pre-2.0 Antistasi support system but encountered some issues so it didn't made into the last Plus update. So, the original code is from old pre-mod Antistasi/Antistasi Plus and I have no idea where they got it.

Be careful with your accusations. ¯\_(ツ)_/¯

**Comment by wersal454** [comment]
> > Original code for gunship probably ̷s̷t̷o̷l̷e̷n̷ acquired by Socrates https://gitlab.com/phillyspall/blackfish-gunship-ai
> 
> Bruh. I haven't stole anything, in fact, you, ahem, _yoinked_ the code from the very WIP and abandoned https://github.com/igorkis-scrts/A3-Antistasi-Plus/tree/feature/gunship branch where I tried to backport gunship code from old, pre-2.0 Antistasi support system but encountered some issues so it didn't made into the last Plus update. So, the original code is from old pre-mod Antistasi/Antistasi Plus and I have no idea where they got it.
> 
> Be careful with your accusations. ¯_(ツ)_/¯

))))))))))))))

**Pull request closed without merging**
