### PR TITLE
A tiny pr now with combined factions

### PR DESCRIPTION
**Pull request by wersal454**
## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:
continuation of #279
```Added no insignia vehicles for SPE and SOG
Added SOG and SPE content for vanilla factions
Moved dlc content to specialized directories containing all content that used in different templates
Moved variants and animations for vehicles in their own directories, so depending on what faction you are making if you using vehicles from dlcs and/or vanilla, you can simply include those files and it would apply desired camo and randomized customization
Changed logic for picking helmets for friendly AI, now AI will equip random helmets if their "armor" points are below 5
Added Mod content directory(mostly same as DLC content) with CUP AAF example
Added CUP AAF content to Vanilla AAF
```

contains fixes for that PR + Added combined vanilla factions

CSAT&AAF - 
```
Canton Protocol Strategic Alliance Treaty and Altis Armed Forces (CSAT and AAF). After NATO forces took over Altis archipelagos, AAF stroke deal with CSAT to return control of their islands, but at the cost of becoming their puppets and dragging their nation in the bigger conflict.
```
NATO&AAF -
```
North Atlantic Treaty Organization and Altis Armed Forces (NATO and AAF). After brutal civil war, Altis government and militiraly were left in ruin. After negotiations with NATO, AAF will receive requested support, but at the cost of their autonomy.
```
NATO&LDF (both Arid and Temperate) -
```
North Atlantic Treaty Organization and Livonian Defense Force (NATO and LDF). After successful combined training in Livonia, tension between CSAT and NATO increased. LDF decided to let NATO build more of their bases to increase their chances if their eastern neighbor will make it's move.
```

Ported https://github.com/official-antistasi-community/A3-Antistasi/pull/3335

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

********************************************************
Notes:

Big thanks to @UAC-MaxxLite for making flags and markers and thanks to @Ravenholme for providing support considering lore stuff

### CODE REVIEW

**Comment by wersal454** [comment]
NATO&UNA
```
North Atlantic Treaty Organization and United Nations Agency (NATO and UNA). After a series of attacks on UN peacekeepers within the Sefrou-Ramal region, some of which were seemingly perpetrated by elements of the SFIA, it was agreed that a NATO task force would provide support to ensure the safety of aid workers and UN staff in the region.
```
CSAT&SFIA
```
Canton Protocol Strategic Alliance Treaty and Sefrawi Freedom and Independence Army (CSAT and SFIA).After recent attacks by Tura forces on SFIA military bases and increasing presence of NATO forces to oversee UN peacekeeping operations, a decision was made by the Arganan government to station CSAT forces in Sefrou-Ramal to bolster regional security.
```

**Comment by wersal454** [comment]
Ported over #3335 to fix CUP & IFA planes turn rates

**Comment by Silence-112** [comment]
Add any community links to your original posts by editing them, will prevent it being forgotten when pulls are merged

**Comment by stutpip123** [comment]
this is so massive idk if we can do anything without just merging and pray it doesnt break too much.
its been in the testingbranch and not caused issues as far as can tell

**Comment by Silence-112** [comment]
I've reverted the `equipmentClassToCategories` change as it was causing helmets to be unlocked by default, if you can find a way to do the AI pick change without that bug then open another PR

**Pull request merged**
