### PR TITLE
Gulfcoast Islands Port

### PR DESCRIPTION
**Pull request by lanoitidart**
## What type of PR is this?
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement
4. [x] Miscellaneous

### What have you changed and why?
Ported the [Gulfcoast Islands](https://steamcommunity.com/sharedfiles/filedetails/?id=1617004814) map to Antistasi Ultimate

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

Proper play testing/edits of nodes to see how convoys function on the map, but other than that it should be fine.

### How can the changes be tested?
Steps:

********************************************************
Notes:

Good to go

### CODE REVIEW

**Review by Silence-112 — APPROVED** [review]
Looks good to me file wise

**Comment by lanoitidart** [comment]
I think I've done everything I can with this map for now. Would need a final review, but I'm happy with what's on there.

**Review by Silence-112 — APPROVED** [review]
Haven't checked the map but otherwise looks fine

**Comment by lanoitidart** [comment]
Issues / changes needed found during playtest:

**Patch 1**
- [x] move vehicle nodes on Flats Castle Ruins - _had a possibility to spawn inside of the flag_
- [x] move vehicle nodes on Lake Haven Airport
- [x] Fix flag location for Resource South East of Haven South Flats - _Flag sometimes spawned inside of a building_
- [x] Fix markers on Orion Military Base - _SAM marker is too close to building and will end up blocking a portion of the road._
- [x] Remove non-native helipads from Orion Airbase - _Spawned on existing and hidden helipads which made two helicopters spawn incredibly close to eachother._
- [x] Move Orion Railways Factory Marker - _Moving marker to a visibly better location_

**Patch 2**

- [ ] Placeholder

**Pull request merged**
